#!/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
BOLD='\e[1m'
NC='\033[0m'

IP=`hostname -I | awk '{print $1}'`

printf "\n _    _  __     __  _____    ______   _____    ____    _              _   _ \n"
printf "| |  | | \ \   / / |  __ \  |  ____| |  __ \  |  _ \  | |     /\     | \ | |\n"
printf "| |__| |  \ \_/ /  | |__) | | |__    | |__) | | |_) | | |    /  \    |  \| |\n"
printf "|  __  |   \   /   |  ___/  |  __|   |  _  /  |  _ <  | |   / /\ \   | . \` |\n"
printf "| |  | |    | |    | |      | |____  | | \ \  | |_) | | |  / ____ \  | |\  |\n"
printf "|_|  |_|    |_|    |_|      |______| |_|  \_\ |____/  |_| /_/    \_\ |_| \_|\n"

printf "\nTo configure Hyperion browse to ${BLUE}http://${IP}:8090${NC} from another device on your network."
printf "\nAll Hyperion configuration can be completed via the Hyperion Web UI.\n\n"

systemctl is-active hyperion@*.service >/dev/null 2>&1 && printf "Hyperion status: ${GREEN}⬤  Running${NC}\n" || printf "Hyperion status: ${RED}⬤  Stopped${NC}\n"

printf "\n${BOLD}* Documentation: ${NC}${GREEN}https://docs.hyperion-project.org${NC}"
printf "\n${BOLD}* Website:       ${NC}${GREEN}https://hyperion-project.org${NC}"
printf "\n${BOLD}* Source:        ${NC}${GREEN}https://github.com/hyperion-project${NC}"



printf "\n\n"
